twig:
    default_path:         '%kernel.project_dir%/templates'
    debug:                '%kernel.debug%'
    strict_variables:     '%kernel.debug%'
    exception_controller: null
    paths:
        '%kernel.project_dir%/assets/css': 'styles'
        '%kernel.project_dir%/assets/img': 'images'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/templates/vich_uploader_form_fields.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@EWZRecaptcha/Form/v3/ewz_recaptcha_widget.html.twig'
    globals:
        google_analytics_enabled: '%google_analytics_enabled%'
        google_analytics_account: '%google_analytics_account%'
        google_calendar_api_key:  '%google_calendar_api_key%'
        facebook_pixel_enabled:   '%facebook_pixel_enabled%'
        facebook_pixel_id:        '%facebook_pixel_id%'
        main_brand_title:         '%project_web_title%'
        main_brand_url:           '%project_url_base%'
        main_brand_email:         '%mailer_destination%'
        main_brand_address:       '%boss_address%'
        main_brand_city:          '%boss_city%'
        main_brand_phone_1:       '%boss_phone_number_1%'
        main_brand_phone_2:       '%boss_phone_number_2%'
        boss_name:                '%boss_name%'
        boss_dni:                 '%boss_dni%'
        boss_city:                '%boss_city%'
        admin_logo:               '%admin_logo%'
        admin_color:              '%admin_color%'
        admin_is_stage:           '%admin_is_stage%'
        admin_tag_version:        'v5.2.05'

when@test:
    twig:
        strict_variables: true
